Update patch set 2
Patch Set 2: Verified-1

This particular patch breaks stuff for me. I've checked I'm fully synced with upstream 14.1 and that's the case, then applied the 2019-04 patch set. Errors:

[ 51% 17951/34789] target arm C: libnfc-nci <= external/libnfc-nci/src/nfc/llcp/llcp_sdp.c
-funwind-tables -fstack-protector-strong -Wa,--noexecstack -Werror=format-security -D_FORTIFY_SOURCE=2 -fno-short-enums -no-canonical-prefixes -mcpu=cortex-a15-UDEBUG  -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -nostdlibinc  -mcpu=krait -mfpu=neon-vfpv4 -target arm-linux-androideabi    -target arm-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-aeturn-type  -MD -MF /var/media/data/code/lineage/14.1/out/target/product/z3c/obj/SHARED_LIBRARIES/libnfc-nci_intermediates/src/nfc/tags/rw_i93.d -o /var/media/data/code/lineage/14.1/out/target/product/z3c/obj/SHARED_LIBRARIES/libnfc-nci_intermediates/src/nfc/tags/rw_i93.o external/libnfc-nci/src/nfc/tags/rw_i93.c ) && (cp /var/media/data/code/lineage/14.1/out/target/product/z3c/obj/SHARED_LIBRARIES/libnfc-nci_intermediates/src/nfc/tags/rw_i93.d /var/media/data/code/lineageexternal/libnfc-nci/src/nfc/tags/rw_i93.c:249:9: error: use of undeclared identifier 'bool'
        bool block_16_bit = p_i93->intl_flags & RW_I93_FLAG_16BIT_NUM_BLOCK;
        ^
external/libnfc-nci/src/nfc/tags/rw_i93.c:255:19: error: use of undeclared identifier 'block_16_bit'
        else if (!block_16_bit && length > 1)
                  ^
                   ^
external/libnfc-nci/src/nfc/tags/rw_i93.c:275:20: error: use of undeclared identifier 'false'
            return false;
                   ^

Patch-set: 2
Reviewer: Gerrit User 18939 <18939@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=-1